// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProyectoChat.Context;

#nullable disable

namespace ProyectoChat.Migrations
{
    [DbContext(typeof(OrgDbContext))]
    [Migration("20260109182557_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProyectoChat.Models.Noticia", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreadorID")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImagenURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("CreadorID");

                    b.ToTable("Noticias");
                });

            modelBuilder.Entity("ProyectoChat.Models.Rol", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = "national",
                            Descripcion = "Acceso total al sistema",
                            Nombre = "National Director"
                        },
                        new
                        {
                            Id = "department",
                            Descripcion = "Administra departamento",
                            Nombre = "Department Director"
                        },
                        new
                        {
                            Id = "municipal",
                            Descripcion = "Administra municipio",
                            Nombre = "Municipal Director"
                        },
                        new
                        {
                            Id = "leader",
                            Descripcion = "Líder de grupo",
                            Nombre = "Leader"
                        },
                        new
                        {
                            Id = "user",
                            Descripcion = "Usuario básico",
                            Nombre = "User"
                        });
                });

            modelBuilder.Entity("ProyectoChat.Models.Usuario", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FormExternoID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("JefeID")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RolId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("JefeID");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProyectoChat.Models.Noticia", b =>
                {
                    b.HasOne("ProyectoChat.Models.Usuario", "Creador")
                        .WithMany()
                        .HasForeignKey("CreadorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creador");
                });

            modelBuilder.Entity("ProyectoChat.Models.Usuario", b =>
                {
                    b.HasOne("ProyectoChat.Models.Usuario", "Jefe")
                        .WithMany()
                        .HasForeignKey("JefeID");

                    b.HasOne("ProyectoChat.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jefe");

                    b.Navigation("Rol");
                });
#pragma warning restore 612, 618
        }
    }
}
