// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProyectoChat.Context;

#nullable disable

namespace ProyectoChat.Migrations
{
    [DbContext(typeof(OrgDbContext))]
    partial class OrgDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProyectoChat.Models.Ciudad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Ciudades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartamentoId = 5,
                            Nombre = "Cartagena"
                        },
                        new
                        {
                            Id = 2,
                            DepartamentoId = 14,
                            Nombre = "Cúcuta"
                        },
                        new
                        {
                            Id = 3,
                            DepartamentoId = 26,
                            Nombre = "San Andrés, Prov. y Santa Catalina"
                        },
                        new
                        {
                            Id = 4,
                            DepartamentoId = 11,
                            Nombre = "Valledupar"
                        },
                        new
                        {
                            Id = 5,
                            DepartamentoId = 15,
                            Nombre = "Bogotá"
                        });
                });

            modelBuilder.Entity("ProyectoChat.Models.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Departamentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Amazonas"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Antioquia"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Arauca"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Atlántico"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Bolívar"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Boyacá"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Caquetá"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Caldas"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Casanare"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Cauca"
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "Cesar"
                        },
                        new
                        {
                            Id = 12,
                            Nombre = "Chocó"
                        },
                        new
                        {
                            Id = 13,
                            Nombre = "Córdoba"
                        },
                        new
                        {
                            Id = 14,
                            Nombre = "Norte de Santander"
                        },
                        new
                        {
                            Id = 15,
                            Nombre = "Cundinamarca"
                        },
                        new
                        {
                            Id = 16,
                            Nombre = "Guainía"
                        },
                        new
                        {
                            Id = 17,
                            Nombre = "Guaviare"
                        },
                        new
                        {
                            Id = 18,
                            Nombre = "Huila"
                        },
                        new
                        {
                            Id = 19,
                            Nombre = "La Guajira"
                        },
                        new
                        {
                            Id = 20,
                            Nombre = "Magdalena"
                        },
                        new
                        {
                            Id = 21,
                            Nombre = "Meta"
                        },
                        new
                        {
                            Id = 22,
                            Nombre = "Nariño"
                        },
                        new
                        {
                            Id = 23,
                            Nombre = "Putumayo"
                        },
                        new
                        {
                            Id = 24,
                            Nombre = "Quindío"
                        },
                        new
                        {
                            Id = 25,
                            Nombre = "Risaralda"
                        },
                        new
                        {
                            Id = 26,
                            Nombre = "San Andrés"
                        },
                        new
                        {
                            Id = 27,
                            Nombre = "Santander"
                        },
                        new
                        {
                            Id = 28,
                            Nombre = "Sucre"
                        },
                        new
                        {
                            Id = 29,
                            Nombre = "Tolima"
                        },
                        new
                        {
                            Id = 30,
                            Nombre = "Valle del Cauca"
                        },
                        new
                        {
                            Id = 31,
                            Nombre = "Vaupés"
                        },
                        new
                        {
                            Id = 32,
                            Nombre = "Vichada"
                        });
                });

            modelBuilder.Entity("ProyectoChat.Models.Noticia", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreadorID")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImagenURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("CreadorID");

                    b.ToTable("Noticias");
                });

            modelBuilder.Entity("ProyectoChat.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Descripcion = "Acceso total al sistema",
                            Nombre = "Director Nacional"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Administra departamento",
                            Nombre = "Director Departamental"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Administra municipio",
                            Nombre = "Director Municipal"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Líder de grupo",
                            Nombre = "Líder"
                        },
                        new
                        {
                            Id = 1,
                            Descripcion = "Usuario básico",
                            Nombre = "Usuario"
                        });
                });

            modelBuilder.Entity("ProyectoChat.Models.Usuario", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CiudadId")
                        .HasColumnType("integer");

                    b.Property<int?>("DepartamentoId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FormExternoID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("JefeID")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("CiudadId");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("JefeID");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProyectoChat.Models.Ciudad", b =>
                {
                    b.HasOne("ProyectoChat.Models.Departamento", "Departamento")
                        .WithMany("Ciudades")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("ProyectoChat.Models.Noticia", b =>
                {
                    b.HasOne("ProyectoChat.Models.Usuario", "Creador")
                        .WithMany()
                        .HasForeignKey("CreadorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creador");
                });

            modelBuilder.Entity("ProyectoChat.Models.Usuario", b =>
                {
                    b.HasOne("ProyectoChat.Models.Ciudad", "Ciudad")
                        .WithMany()
                        .HasForeignKey("CiudadId");

                    b.HasOne("ProyectoChat.Models.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("DepartamentoId");

                    b.HasOne("ProyectoChat.Models.Usuario", "Jefe")
                        .WithMany()
                        .HasForeignKey("JefeID");

                    b.HasOne("ProyectoChat.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ciudad");

                    b.Navigation("Departamento");

                    b.Navigation("Jefe");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ProyectoChat.Models.Departamento", b =>
                {
                    b.Navigation("Ciudades");
                });
#pragma warning restore 612, 618
        }
    }
}
